### ISSUE TITLE
listing of stands without service stands

### ISSUE THREAD

**Issue by MichalPP** [cyklokoalicia/OpenSourceBikeShare#129]
`command.php?action=map:markers` should return only stands which are available for general use (so service stands should be removed, or marked as unavailable in some way other than name).

**Comment by nekromoff** [comment]
This is regarding `breakthrough` release that has not been developed for some time. Laravel version has priority instead, any testing should be done on the `develop` branch.

**Comment by MichalPP** [comment]
where should I put this issue? afaik it is impossible to add issues to branches

**Comment by nekromoff** [comment]
Branch is not developed anymore, but you are welcome to do the pull request
with the change.

**Comment by MichalPP** [comment]
which branch is developed? where should I put this issue?

**Comment by jozefbalun** [comment]
develop, and add label laravel

**Comment by MichalPP** [comment]
as I've noted above, it is impossible to add issues to branches and I (as non root) cannot add labels.

**Comment by jozefbalun** [comment]
ok, I created new issue for laravel version #130

**Comment by andrewshadura** [comment]
None of this makes sense to me. In GitHub, bugs apply to the whole repository, there isn't any way to specifically create a bug which would apply to a branch only, and @MichalPP hasn't done anything wrong. There wasn't need to open a new issue.
