### ISSUE TITLE
Not allowed to connect to this MySQL server

### ISSUE THREAD

**Issue by PieterjanDG** [cyklokoalicia/OpenSourceBikeShare#135]
If I run the Develop branch with docker, I get it running. But if I go to register, fill in personal data to register and then click on Register, it gives the following error:
SQLSTATE[HY000] [1130] Host '172.21.0.3' is not allowed to connect to this MySQL server (SQL: select count(*) as aggregate from `users` where `email` = ... )

How can I solve this?

**Comment by sveneld** [comment]
Laravel project is closed
