### ISSUE TITLE
Logout page redirect stored in browser cache

### ISSUE THREAD

**Issue by ewooonk** [cyklokoalicia/OpenSourceBikeShare#136]
The logout page 301 redirect is saved in the browser cache. Therefore the user cannot logout a second time. Redirect needs to be changed to:

`header('Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0');      
   header("HTTP/1.1 303 See Other")`

**Comment by nekromoff** [comment]
302 is the correct code, not 303

**Comment by nekromoff** [comment]
fixed by the latest commit/pull request, closing
