### ISSUE TITLE
Unable to start the Laravel app

### ISSUE THREAD

**Issue by eronisko** [cyklokoalicia/OpenSourceBikeShare#141]
On branch `develop`, every artisan command (e.g. `php artisan package:discover`) comes back with:
```
In Router.php line 342:

  Type error: Argument 1 passed to Illuminate\Routing\Router::group() must be of the type array, string given, called in C:\Users\eronisko\workspace\OpenSourceBikeShare\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 221
```

I've tried googling for the error to no avail. I've also tried `composer update`, no luck there either.

I couldn't find any explicit calls to `Router::group()` in the app itself, so I'm suspecting it's one of the dependencies. Unfortunately I don't know artisan/composer well enough to investigate this further.

**Comment by sveneld** [comment]
Migration to Laravel is rejected. Another way of project evolution selected
