### ISSUE TITLE
Where do I find the current app?

### ISSUE THREAD

**Issue by eronisko** [cyklokoalicia/OpenSourceBikeShare#142]
Hi, I'd like to help out with development/maintenance of the web app but I'm not sure where to begin.

I've managed the get the breakthrough branch running, but it doesn't seem to fully match the the app I'm seeing as a user at [whitebikes.info](https://whitebikes.info).

I've also tried running the develop branch, but I'm [unable to get the app to work](#141).

Where can I find the current deployed version of this app?

**Comment by nekromoff** [comment]
Breakthrough is the current one, although Bratislava code might have some custom updates. @mmmaly will be able to push them to start a new branch including them.

**Comment by eronisko** [comment]
Hi @mmmaly, would you be able to push Bratislava code up here?

**Comment by sveneld** [comment]
Too much time went from the first message in this topic %)
I joined to the whitebikes team and will try to give a new breath to this project. I will start with cleanup. All custom code which is located on site will be reviewed and pushed to the branch **breakthrough**

**Comment by sveneld** [comment]
breakthrough branch is set as default and renamed to main. code from whitebikes will be added to main branch after merging of this pull request https://github.com/cyklokoalicia/OpenSourceBikeShare/pull/159
