### ISSUE TITLE
Delete old branches

### ISSUE THREAD

**Issue by sveneld** [cyklokoalicia/OpenSourceBikeShare#157]
There is too many old branches which is useless now.
Here it is the list of this branches with maintainers. If you think that your code/branch should be left - update your branch and create a pull request with code.
I think one week is enough to decide future of your branch, if you need more time write in this issue. After one week old branches will be removed.

My plan with update of this project:
- Remove broken branches 
- Remove unfinished projects 
- Make cleanup on hosting 
- Fix minor bugs 
- Migrate to php 7.4 or higher 
- Add docker instance 
- Add composer
- Add unit tests
- Migrate to symfony framework
- Etc

[actions-sms](https://github.com/cyklokoalicia/OpenSourceBikeShare/tree/actions-sms) @martinsmid
[feature/add_coupons](https://github.com/cyklokoalicia/OpenSourceBikeShare/tree/feature/add_coupons) @jozefbalun
[feature/long_rent_service](https://github.com/cyklokoalicia/OpenSourceBikeShare/tree/feature/long_rent_service) @jozefbalun
[feature/sms_notifications](https://github.com/cyklokoalicia/OpenSourceBikeShare/tree/feature/sms_notifications) @jozefbalun
[feature/activity_logs](https://github.com/cyklokoalicia/OpenSourceBikeShare/tree/feature/activity_logs) @jozefbalun
[feature/add_support_for_qr_codes](https://github.com/cyklokoalicia/OpenSourceBikeShare/tree/feature/add_support_for_qr_codes) @jozefbalun 
[servicenorent](https://github.com/cyklokoalicia/OpenSourceBikeShare/tree/servicenorent) @mmmaly
[develop-miroc](https://github.com/cyklokoalicia/OpenSourceBikeShare/tree/develop-miroc) @miroc
[develop-old-frontend](https://github.com/cyklokoalicia/OpenSourceBikeShare/tree/develop-old-frontend) @miroc
[mapka](https://github.com/cyklokoalicia/OpenSourceBikeShare/tree/mapka) @miroc
[cities](https://github.com/cyklokoalicia/OpenSourceBikeShare/tree/cities) @mmmaly
[master](https://github.com/cyklokoalicia/OpenSourceBikeShare/tree/master) @mmmaly
[develop](https://github.com/cyklokoalicia/OpenSourceBikeShare/tree/develop) @nekromoff

**Comment by mmmaly** [comment]
Yes, my old branches can be deleted.

**Comment by sveneld** [comment]
All old branches deleted
