### ISSUE TITLE
prepared sql commands

### ISSUE THREAD

**Issue by mmmaly** [cyklokoalicia/OpenSourceBikeShare#4]
rewrite sqls to prepared statements

**Comment by nekromoff** [comment]
under complete rewrite now (migration to PDO)

**Comment by nekromoff** [comment]
@martinsmid let me know, when everything is rewritten, so we can close this. thanks!

**Comment by martinsmid** [comment]
Sure, I will need some help with testing.

**Comment by nekromoff** [comment]
no problem, let me know, when rewritten and we will do the testing. Also
you will probably need new API codes, I'll put that together.
