### ISSUE TITLE
Revamp UI

### ISSUE THREAD

**Issue by jurajk** [cyklokoalicia/OpenSourceBikeShare#40]
when backend functionality gets somewhat stable, let me know. will take care of the UI.

**Comment by nekromoff** [comment]
![screen-fleet](https://cloud.githubusercontent.com/assets/8550349/8681566/95786e96-2a68-11e5-8439-142fc6fa2857.png)

**Comment by mozares** [comment]
nice one! I will take this as a project for me in Autumn after mobility week, if it will be not provided before by somebody else. Pls. prepare me possible interactions.

**Comment by nekromoff** [comment]
now is a good time to create a template.

**Comment by mozares** [comment]
good Idea. Lets organize UI/UX flow meeting and then I can design
everything.
