### ISSUE TITLE
web rent with location number as well

### ISSUE THREAD

**Issue by MichalPP** [cyklokoalicia/OpenSourceBikeShare#75]
if you click on rent button via web interface, it is possible that the bike was already rented (due to bad caching of the browser). the rent request should send bike number and location number. if the browser version and database version don't match, return error.

**Comment by nekromoff** [comment]
please, suggest concrete fingerprinting algo and i will implement that
unfortunately, android browsers are overzealous in caching, even if no-cache set

**Comment by MichalPP** [comment]
from user point of view, current situation:
1. in web UI i open my stand, I check if there is a bike. (I pack my stuff, leave house).
2. I click on rent. browser sends rent request witch bike number, 
3. I receive pin code.
4. I arrive at the stand, the bike is not there because I wasn't refreshing my browser. 
5. I try to find the new stand of my rented bike, change pin...

new situation:
1. the same
2. I click on rent. browser sends rent request with bike number AND stand name
3. I receive reply 'your requested bike is no longer at given stand'.
4. I come to the stand and visually check available bike numbers..

https://github.com/mmmaly/OpenSourceBikeShare/blob/master/receive.php should include option 'rent with bike number and stand name' (or in action-web.php)

and the web app should silently send bike number AND also stand name.

**Comment by nekromoff** [comment]
possible situation, but rules (whitebikes etc.) require user to come to the stand and visually inspect available bicycles before renting, although as any rules, these are also sometimes not respected by the users, so you have valid point.
