### ISSUE TITLE
meaning of privileges

### ISSUE THREAD

**Issue by exmatrikulator** [cyklokoalicia/OpenSourceBikeShare#80]
What is the idea behind the numbers of the privileges?
Or what is the meaning of the numbers from 0 to 7?

**Comment by nekromoff** [comment]
0 - regular user
1 - admin
3 - superadmin

i think, you could probably find 2 used for serviceman that does not have
admin rights, but i am not sure at this moment. privileges system needs
kind of sorting out.

**Comment by exmatrikulator** [comment]
thanks for the quick responce.
in the  INSTALL.md it is said that 7 is an admin.
i would be verry happy, if there is a list with used (and planed) privileges.

**Comment by Medanaresh** [comment]
how admin can change cycles from one stand to another stand. Option is there..

**Comment by nekromoff** [comment]
As the rewrite is currently underway, privileges will be clearly stated once this is done.

**Comment by sveneld** [comment]
Migration to Laravel is rejected. Another way of project evolution selected
