### ISSUE TITLE
Adding a framework

### ISSUE THREAD

**Issue by ondrejkoren** [cyklokoalicia/OpenSourceBikeShare#82]
I'm seriously thinking about contributing to this project. I'd strongly suggest to use a proper framework, if you want to support scalability and reliability and this project to be more maintainable and supported.

If you want to stick to PHP (which I discourage), I'd suggest popular, well-supported PHP web frameworks like CakePHP, Yii or CodeIgniter (for a more minimalistic approach).

If you'd want to consider a different platform, which would still be supported (like Java's Play 2 framework) or very robust Python's flask, or even the popular Ruby on Rails platform, I'd be happy to rewrite the current base into a platform+framework.

**Comment by nekromoff** [comment]
Hello,

thank you for your suggestions.

I am currently rewriting OSBS to RedBeanPHP (ORM) to solve identified security issues that we have known about for longer time, but didn't have time to fix due to the fast pace of functionality developments.

We are sticking to PHP and I have already considered a framework, but took no decision on whether to use one and which one to use so far. CakePHP is overkill for such small project in my opinion and we need some kind of small footprint framework.

You are welcome to contribute, if you are OK to work with PHP (and PHP framework).

**Comment by ondrejkoren** [comment]
Then I would suggest CodeIgniter, since it has no ORM, your effort wouldn't be wasted and could be combined. Also it is a small framework, possibly ideal for a project this scale (although note that the functionality can grow and the framework will have to meet the needs!).

If there'd be a decision to rewrite to CodeIgniter, I will happily do it, I have lots of experience with it. Let me know. Thank you!

**Comment by nekromoff** [comment]
OK, I will check it out and let you know - your effort is appreciated!

**Comment by nekromoff** [comment]
what do you think about something more lightweight, such as:
https://github.com/bcosca/fatfree
https://github.com/popphp/popphp
http://www.slimframework.com (v2 looks interesting, v3 complicates things a bit)

**Comment by ondrejkoren** [comment]
CodeIgniter is already VERY lightweight. It just adds transparency and a clearly defined of way how to structure and organise the repository. CodeIgniter is also on GitHub and has 360+ contributors (compared to 10, 1, or 90) and over 8k commits and is officially backed up by the British Columbia Institute of Technology. It has a large community on stackoverflow, or generally on the internet and a strong community somewhat guarantees a strong tool. Also, it's been around long enough to go through a lot.

Also the use of a popular and well-known framework is much more likely to attract contributors, rather than some 1-man-framework without documentation and support. We could argue that you can fix a bug in an open-source project, but let's face it. You want to build with a tool, not fixing the tool itself.

I believe these are all very relevant factors to consider, if this project should have a firm codebase that it can stand on an expand.

Now, I am not enforcing or trying to go with CI at all cost, there are other great PHP frameworks. I just you see the case I am trying to make here.

Cheers!

**Comment by nekromoff** [comment]
well, I guess CodeIgniter seems fine and code is readable.

**Comment by ondrejkoren** [comment]
OK. I will create a first draft with CodeIgniter in my fork, that can be then reviewed and after consideration pulled into this repo.

I will notify.

**Comment by kuchy** [comment]
I suggest [nette](https://nette.org/en/), with [doctrine2 ORM](https://github.com/Kdyby/Doctrine). Based on my experienced better than CodeIgniter (but I was working with only really old versions).

**Comment by nekromoff** [comment]
We have been now thinking about Laravel, I think nette is a bit too heavy for our purpose.

2015 framework popularity results (Laravel vs nette):
https://www.sitepoint.com/best-php-framework-2015-sitepoint-survey-results/

**Comment by pato1** [comment]
[Laravel](https://laravel.com) is by many developers considered to be the best FW at the time. 
I personally think it's not just about the framework, but more about using great design patterns, established by the world's best programmers.  Laravel is doing a very good job at that.

**Comment by freezy-sk** [comment]
Symfony with Doctrine should be better choice than Nette or overhyped Laravel (which is built on top of Symfony)
