### ISSUE TITLE
about  map

### ISSUE THREAD

**Issue by Medanaresh** [cyklokoalicia/OpenSourceBikeShare#91]
hi, is it possible to show the path from station to another station on map, i am not asking about walking directions.

**Comment by MichalPP** [comment]
do you mean highlighted recommended routes among stations? NxN routes, or just the closest ones?

do you mean walking or bicycling path?

**Comment by Medanaresh** [comment]
i am  asking highlighted recommended routes among stations, by default  in map it shows the station place, i am asking the path between stations,
